drop table IF EXISTS comments cascade;
drop table IF EXISTS bookings cascade;
drop table IF EXISTS items cascade;
drop table IF EXISTS requests cascade;
drop table IF EXISTS users cascade;

CREATE TABLE IF NOT EXISTS users
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(100) NOT NULL,
    email varchar(320) NOT NULL,
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email),
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS requests
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR(1000) NOT NULL,
    requestor_id BIGINT REFERENCES users (id),
    created TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_request PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS items
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(100) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    available boolean,
    owner_id BIGINT references users (id),
    request_id BIGINT references requests(id),
    CONSTRAINT pk_item PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date timestamp without time zone NOT NULL,
    end_date timestamp without time zone NOT NULL,
    item_id BIGINT references items (id),
    booker_id BIGINT references users (id),
    status varchar (50),
    CONSTRAINT pk_booking PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text VARCHAR(100) NOT NULL,
    item_id BIGINT  references items (id),
    author_id BIGINT  references users (id),
    created timestamp without time zone,
    CONSTRAINT pk_comments PRIMARY KEY (id)
);